### ISSUE TITLE
evaluate.txt

### ISSUE THREAD

**Issue by psalias2006** [myNBGcode/word-embedding-evaluation#1]
Hey! I think you miss evaluate.txt

**Comment by bognick** [comment]
Hi Panos. Actually we didn't miss to upload the text on which we're going to evaluate the participations. The reason that we do not share it is because we do not want you to overfit on our evaluation text. You should use any Greek texts that you want, I believe a variety of legal texts would be both in context and would allow your embedding to generalize well.
